### ISSUE TITLE
Sound and video doesn`t play on Amazon Fire Phone

### ISSUE THREAD

**Issue by onix-adt** [amzn/exoplayer-amazon-port#10]
Playing audio on Amazon Fire Phone cause noises.
https://youtu.be/si8o7P3qExs

Build demos and run any audio or video with audio.
After playing started it fast going to end.
Its reproduced all times with MediaCodec and Ffmpeg Audio renders.

**Comment by peddisri** [comment]
Hi,
Unfortunately, the Fire Phone I have is not working.  Can you try this change in your code base and let me know if it worked? 

In AmazonQuirks.java

**private static final String FIRE_PHONE_DEVICE_MODEL = "SD";
private static final boolean isFirePhone;**
static {
 **isFirePhone = isAmazonDevice && DEVICEMODEL.startsWith(FIRE_PHONE_DEVICE_MODEL);**
.
.
}
public static boolean isLatencyQuirkEnabled() {
// Sets latency quirk for Amazon KK and JB Tablets
   return ( (Util.SDK_INT <= 19) && (isKindleTablet **|| isFirePhone**) );
}

**Comment by onix-adt** [comment]
You right, its really helpful. Take a look at result:
https://gist.github.com/onix-adt/2193950c3ed5e0ea17614b248e44aafe

**Comment by peddisri** [comment]
I've pushed a change to all latest branches.
