### ISSUE TITLE
Matching Content Frame rate

### ISSUE THREAD

**Issue by neverased** [amzn/exoplayer-amazon-port#100]
Hi, just a quick question.

I am trying to play some custom streams with different resolutions and frame rates (ie. FHD, UHD, 50fps, 59,94fps) and verify if matching content frame rate actually works on Amazon Fire TV Stick 4K.

It seems that no matter what setting are are actually chosen the output always stays 4K60 (Auto resolution, matching content frame rate ON) . Even though debug info in app says that video stream is 1920x1080 - HDMI output is always locked on 4K60. (grabbed and checked with Professional HDMI analyzer).

Is there anything I can do in-app to actually make it matching content frame rate / resolution ?

I would be grateful for any advice.

Best,
Wojciech

**Comment by Sau28** [comment]
Hey, 

You are changing the "video resolution" and "match content frame rate" under the display settings. 
To fetch display size under display settings, you can use getPhysicalDisplaySize() API: https://github.com/amzn/exoplayer-amazon-port/blob/e2a7039682e75343f4cd1713ff15d74cc983e397/library/core/src/main/java/com/google/android/exoplayer2/util/Util.java#L1842-L1889  
These settings do not change the resolution or frame rate at which the content plays on the ExoPlayer.
This issue https://github.com/google/ExoPlayer/issues/6125 talks about changing stream quality. You can check if it serves your purpose.

**Comment by zsmatyas** [comment]
HDMI mode switch is a negotiation between the Fire TV device and the connected HDMI sink - it takes several seconds based on your sink.

The setting "match content frame" only affects the built in Fire TV applications - and all those will have a fixed FPS without letting the users adjust playback speed.

ExoPlayer lets you play any frame rate, adapt between various options possibly having different FPS and arbitrarily adjust the playback speed. All these parameters affect the real frame rate. As each HDMI mode switch would take several seconds to get applied (and the TV shows a black screen during that period) the platforms cannot simply follow the frame rate changes made by the applications by initiating a mode switch. The logic must be inside the application.

You can implement a similar functionality with the Android APIs described here:
https://developer.amazon.com/docs/fire-tv/4k-apis-for-hdmi-mode-switch.html#hdmimodeswitch

**Comment by neverased** [comment]
Thank you for all the answers! It was very helpful.

**Comment by infinity85** [comment]
@zsmatyas 
> HDMI mode switch is a negotiation between the Fire TV device and the connected HDMI sink - it takes several seconds based on your sink.
[...]
> You can implement a similar functionality with the Android APIs described here:
> https://developer.amazon.com/docs/fire-tv/4k-apis-for-hdmi-mode-switch.html#hdmimodeswitch

Sorry for bringing this up again...

I just wanted to ask if this mentioned "hdmimodeswitch" is the same as the so called "cinema mode" which corresponds to automatic refresh rate matching introduced in the newer Fire TV devices? Or is the "cinema mode" respectively "auto frame rate matching" (which can be found in FireTV settings and shows a splash screen upon switching frame rate) something proprietary that can only be accessed and utilized by the original prime video app?

Thank you in advance for your help
