### ISSUE TITLE
Upgrade to exoplayer r2.11.4

### ISSUE THREAD

**Issue by NicolaVerbeeck** [amzn/exoplayer-amazon-port#103]
Any timeline for the upgrade to latest exoplayer release? We are dependant on some new functionality released there

**Comment by rinoshs** [comment]
Which specific functionality in r2.11.4 is required?

**Comment by NicolaVerbeeck** [comment]
- Catch and log exceptions in TextRenderer rather than re-throwing. This allows playback to continue even if subtitle decoding fails (#6885).
- Update the manifest URI to avoid repeated HTTP redirects (#6907).
- Parse period AssetIdentifier elements.

**Comment by NicolaVerbeeck** [comment]
Any news on this? In the meanwhile exoplayer has released 2.11.5

**Comment by aureobeck** [comment]
We are interested in these updates as well, there was substantial changes on the latest versions of Exoplayer, if you could please give some feedbacks when this should be updated, it's on 2.11.7 already, thanks!

**Comment by NicolaVerbeeck** [comment]
Given that we can no longer wait, I took a diff from the amazon changes in 2.11.3 and applied these on top of exoplayer 2.11.7. Commit -> https://github.com/icapps/exoplayer-icapps-port/commit/a17c122191ee13aabe111a9744802430740635cf
These changes have not been verified yet

**Comment by jkwiz** [comment]
@rinoshs r2.11.5 has a crash fix affecting some devices.

https://github.com/google/ExoPlayer/issues/7234

**Comment by lwld** [comment]
In the meantime there's ExoPlayer 2.12.0 on Google, would suggest to update directly there. (see #107)

**Comment by rinoshs** [comment]
Will combine and track with isssue #107 

https://github.com/amzn/exoplayer-amazon-port/issues/107
