### ISSUE TITLE
How to add x-ray feature

### ISSUE THREAD

**Issue by sumanthkumarps** [amzn/exoplayer-amazon-port#104]
X-Ray identifies actors, of particular movie or show. how to add this feature to the player.

![](https://i.pinimg.com/originals/96/46/2b/96462bbd84bc8cbda6242665c41a7247.jpg)

**Comment by zsmatyas** [comment]
As far as I understand X-Ray shows information that is available on imdb.com for the movie you are watching in Amazon Instant Video. Both of these are owned by Amazon. 

I am afraid you will be very limited how you are legally allowed to use information from IMDB in any product. Most probably you will need to pick a different source for meta-data. There are a handful websites out there collecting information about movies, you will need to consult the legal statement of those websites about allowed usage and integration.

After this, you will need to implement the integration of the meta-data into your exoplayer based application, I am not sure we are able to assist with this directly.

**Comment by sumanthkumarps** [comment]
Okay thanks for the information
