### ISSUE TITLE
Update to Exoplayer 2.12 / 2.13 / 2.14

### ISSUE THREAD

**Issue by lwld** [amzn/exoplayer-amazon-port#107]
Google ExoPlayer v2.12.0 has recently been released with many changes / improvements (https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md). In order to be able to use the latest features in Google ExoPlayer, apps using both Google and Amazon builds would need an updated Amazon port (for API compatibility)

### [REQUIRED] Use case description
Upgrade app to use ExoPlayer 2.12 in both Google and Amazon builds

### Proposed solution
Upgrade Amazon port to version 2.12.x of ExoPlayer

### Update ExoPlayer 2.13
ExoPlayer 2.13 has been released. Would be good to also release 2.13.x here.

### Update ExoPlayer 2.14
ExoPlayer 2.14 has been released. Would be good to also release 2.14.x here.

**Comment by rinoshs** [comment]
Request noted, we will provide an update by end of October.

**Comment by IanDBird** [comment]
Just to say we're a +1 on this!

**Comment by ebr11** [comment]
Hi.  Can you outline the changes that are still necessary here?  It seems newer versions of standard Exo work fine on most Amazon devices.

Thanks for any details you can provide.

**Comment by IanDBird** [comment]
For us, we still have a large user base on Fire TV Sticks (v1) that are playing AC3. The key commit for us is this one: https://github.com/amzn/exoplayer-amazon-port/commit/b249b812d49726fbc269925d1addf0aa57d63bf3

**Comment by ebr11** [comment]
> For us, we still have a large user base on Fire TV Sticks (v1) that are playing AC3. The key commit for us is this one: [b249b81](https://github.com/amzn/exoplayer-amazon-port/commit/b249b812d49726fbc269925d1addf0aa57d63bf3)

Interesting.  I see no issues with regular DD and even DD+ in 5.1 format on a V1 Stick.  DD+ 7.1, however, stutters badly.

**Comment by jandresakis** [comment]
@rinoshs Is there a dev branch with the current work in progress that we can try out?

**Comment by ebr11** [comment]
Do you still think you will make this deadline?

**Comment by IanDBird** [comment]
@rinoshs - Any update on when you think you'll have the update available?

**Comment by TombWater** [comment]
There were some commits on the r2.12.1 branch on 11 Nov 2020.
1. Is that version ready for use?
2. Could you please put it on JCenter?
3. Any expectations about porting 2.12.2 yet?

**Comment by lwld** [comment]
ExoPlayer is at r2.12.3 in the meantime... @rinoshs or @aditya-gu any update on releasing this?

**Comment by BuddahLD** [comment]
Hi people!
Are there any updates on the `r2.12.1`?
It will be great to have it on the `JCenter`!

**Comment by lwld** [comment]
ExoPlayer 2.13 has just been released. Would be good to also release 2.13 here.
https://github.com/google/ExoPlayer/releases/tag/r2.13.0

**Comment by lwld** [comment]
https://github.com/google/ExoPlayer/releases/tag/r2.13.1

**Comment by lwld** [comment]
https://github.com/google/ExoPlayer/releases/tag/r2.13.2

**Comment by TrebuhD** [comment]
any updates on this? It would be nice to get the current version on Amazon as well.

**Comment by lwld** [comment]
https://github.com/google/ExoPlayer/releases/tag/r2.13.3

**Comment by dani3l3** [comment]
Any update? trying to fetch from jcenter breaks.
From maven it works

        maven {
            url  "https://dl.bintray.com/exo-support-amzn/amazon-exoplayer-port"
        }

**Comment by nielsvanvelzen** [comment]
https://github.com/google/ExoPlayer/releases/tag/r2.14.0

**Comment by suriyamohansekaran** [comment]
> Google ExoPlayer v2.12.0 has recently been released with many changes / improvements (https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md). In order to be able to use the latest features in Google ExoPlayer, apps using both Google and Amazon builds would need an updated Amazon port (for API compatibility)
> 
> ### [REQUIRED] Use case description
> Upgrade app to use ExoPlayer 2.12 in both Google and Amazon builds
> 
> ### Proposed solution
> Upgrade Amazon port to version 2.12.x of ExoPlayer
> 
> ### Update ExoPlayer 2.13
> ExoPlayer 2.13 has been released. Would be good to also release 2.13.x here.
> 
> ### Update ExoPlayer 2.14
> ExoPlayer 2.14 has been released. Would be good to also release 2.14.x here.

Amazon port of ExoPlayer 2.13.3 has been released and can be found [here](https://github.com/amzn/exoplayer-amazon-port). There is no plan to release ExoPlayer external port for version 2.14

**Comment by nielsvanvelzen** [comment]
> There is no plan to release ExoPlayer external port for version 2.14

Do you have a source for this?

**Comment by dani3l3** [comment]
> > Google ExoPlayer v2.12.0 has recently been released with many changes / improvements (https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md). In order to be able to use the latest features in Google ExoPlayer, apps using both Google and Amazon builds would need an updated Amazon port (for API compatibility)
> > ### [REQUIRED] Use case description
> > Upgrade app to use ExoPlayer 2.12 in both Google and Amazon builds
> > ### Proposed solution
> > Upgrade Amazon port to version 2.12.x of ExoPlayer
> > ### Update ExoPlayer 2.13
> > ExoPlayer 2.13 has been released. Would be good to also release 2.13.x here.
> > ### Update ExoPlayer 2.14
> > ExoPlayer 2.14 has been released. Would be good to also release 2.14.x here.
> 
> Amazon port of ExoPlayer 2.13.3 has been released and can be found [here](https://github.com/amzn/exoplayer-amazon-port). There is no plan to release ExoPlayer external port for version 2.14


Where do we actually have to get it from ? It's nice that you have the source on github, but I mean which repository to specify in build.gradle to actually import the package in our apps?

Even the unofficial source I was using/I posted earlier is gone...

**Comment by lwld** [comment]
@dani3l3 maven central seems to work now, I'm using:
```
    repositories {
        mavenCentral()
    }
```
with `implementation 'com.amazon.android:exoplayer-common:2.13.3'`

**Comment by dani3l3** [comment]
> @dani3l3 maven central seems to work now, I'm using:
> 
> ```
>     repositories {
>         mavenCentral()
>     }
> ```
> 
> with `implementation 'com.amazon.android:exoplayer-common:2.13.3'`

Thanks, this works. Much appreciated.

**Comment by lwld** [comment]
> There is no plan to release ExoPlayer external port for version 2.14

Since 2.13.3 is available and as there is no plan to update for 2.14, this ticket can be closed?

I created a new one for 2.15: #116

**Comment by dani3l3** [comment]
For my perspective I guess it was answered/can be closed.
For the time being we'll keep the Amazon-specific projects on 2.13.3 for another while... it's stable and for the moment I don't need to run after each and every version for the sake of it... I had updated 2.14 on the standard droid version of my app, but in the meantime Google also released 2.15 (which changes some stuff/api names and parameters so some things have to be rewired... https://github.com/google/ExoPlayer/releases/tag/r2.15.0 )... I need to catch my breath, too. 
I'll probably keep both apps  (the 'standard' android/google one and the amazon version of the same) back with the respective currently used version (2.14 and 2.13) for a while if I don't need specific new features, at least in the short period... when I will have a need for it and time, I'll tackle the 2.15 on the standard droid version and see what it brings. The Amazon-specific version of my app DOES require the Amazon-specific port, though, since we have a lot of users connecting to our service thru the oldest FIreTV sticks AFTT which, I was told, behave more reliably with than with the vanilla ExoPlayer. I would not want to make half of my Amazon users mad at me so for now that can and will stay at 2.13.3.

**Comment by lwld** [comment]
In the meantime, version `2.16.1` of the port was released, see #116.

Closing this ticket as it's obsolete.
