### ISSUE TITLE
Migrate hosting repo from JCenter

### ISSUE THREAD

**Issue by nashcft** [amzn/exoplayer-amazon-port#113]
JCenter will stop accepting new submission from Mar. 31st, 2021, and then will be closed in Feb. 1st, 2022.

article from JFrog: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

### [REQUIRED] Use case description

Publish and download packages of exoplayer-amazon-port after JCenter has stopped its service.

### Proposed solution

Migrate to another hosting service like MavenCentral.

**Comment by saumya-y** [comment]
We have migrated to MavenCentral. 
2.12.1 and 2.13.3 can be found there. 

https://repo1.maven.org/maven2/com/amazon/android/exoplayer/
