### ISSUE TITLE
Release 2.12.1 missing jcenter artifacts for common and extractor

### ISSUE THREAD

**Issue by JRFrampton** [amzn/exoplayer-amazon-port#114]
Before filing a bug:
-----------------------
- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website, which can be found at https://exoplayer.dev/.
  It provides detailed information about supported formats and devices.
- Learn how to create useful log output by using the EventLogger:
  https://exoplayer.dev/listening-to-player-events.html#using-eventlogger
- Rule out issues in your own code. A good way to do this is to try and
  reproduce the issue in the ExoPlayer demo app. Information about the ExoPlayer
  demo app can be found here:
  http://exoplayer.dev/demo-application.html.

When reporting a bug:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Issue description
Describe the issue in detail, including observed and expected behavior.

Including the amazon ExoPlayer port artifact fails with 2.12.1 due to missing exoplayer-common and exoplayer-extractor.
`implementation com.amazon.android:exoplayer:2.12.1`

Causes:
`Could not find com.amazon.android:exoplayer-common:2.12.1.`
`Could not find com.amazon.android:exoplayer-extractor:2.12.1.`

Looking at the [maven browser for exoplayer-core](https://mvnrepository.com/artifact/com.amazon.android/exoplayer-core/2.12.1), it mentions both exoplayer-common and exoplayer-extractor as compile dependencies but I don't see them listed under [the com.amazon.android package](https://mvnrepository.com/artifact/com.amazon.android).

The same [browser for exoplayer-core](https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer-core/2.12.1) on the Google side does have links to it under their own repository.

2.11.3 using the same method works as expected.

Is it possible to make these artifacts available?

### [REQUIRED] Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub.

Try to include amazon exoplayer 2.12.1 like so: `implementation com.amazon.android:exoplayer:2.12.1`

### [REQUIRED] Link to test content
Provide a JSON snippet for the demo app’s media.exolist.json file, or a link to
media that reproduces the issue. If you don't wish to post it publicly, please
submit the issue, then email the link to dev.exoplayer@gmail.com using a subject
in the format "Issue #1234", where "#1234" should be replaced with your issue
number. Provide all the metadata we'd need to play the content like drm license
urls or similar. If the content is accessible only in certain countries or
regions, please say so.

N/A

### [REQUIRED] A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234", where "#1234" should be replaced with your issue number.

N/A

### [REQUIRED] Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

N/A

**Comment by carlospontual** [comment]
Do we have any ETA on this? Maybe you know @rinoshs ?

**Comment by paceraudio** [comment]
I am also running into this trying to update from amazon ExoPlayer 2.11.3 to 2.12.1

**Comment by martin-price87** [comment]
Same issue

**Comment by JohnMars** [comment]
Same for us, we need a changes from 2.12.+ on ExoPlayer, but got stuck with this issue.

**Comment by adrian-wozniak** [comment]
Moreover, please publish ExoPlayer artifacts to MavenCentral. JCenter is shut down, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ and https://blog.gradle.org/jcenter-shutdown.

**Comment by dani3l3** [comment]
Me too! :-) Really, we need the update..... we all seem to have already working code done in standard android with the regular exoplayer that needs porting.... and new classes are missing, etc etc.... in particular I am in need of  com.google.android.exoplayer2.MediaItem and com.google.android.exoplayer2.util.Util ...

**Comment by dani3l3** [comment]
Any update? trying to fetch from jcenter breaks.
From maven it works

    maven {
        url  "https://dl.bintray.com/exo-support-amzn/amazon-exoplayer-port"
    }

**Comment by lwld** [comment]
Maven Central seems to work now for `2.13.3`, I'm using:

```
    repositories {
        google()
        mavenCentral()
    }
```
with `implementation 'com.amazon.android:exoplayer-common:2.13.3'`

**Comment by saumya-y** [comment]
Artifacts can be fetched from mavenCentral. 
https://repo1.maven.org/maven2/com/amazon/android/exoplayer/
