### ISSUE TITLE
2.18.0 version not working

### ISSUE THREAD

**Issue by baiqindotfubotv** [amzn/exoplayer-amazon-port#121]
If you declare this dependency it won't work:

implementation 'com.amazon.android:exoplayer:2.18.0'

The error is:
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.amazon.android:exoplayer-ui:2.18.0.

The latest version of the transitive dependency exoplayer-ui is not updated to 2.18.0. (It is still 2.17.1).

**Comment by sbbanore** [comment]
Hi @baiqindotfubotv - Thanks for reporting the issue. As a part of 2.18.0 Google has decoupled exoplayer-ui dependency in the commit - https://github.com/google/ExoPlayer/commit/b2a5298e27a4a2a896d8fa90dd894a7ec12fc50d Hence the dependency is currently not present in the existing artifacts for 2.18.0. We are planning an uplevel on top of 2.18.1 version which should resolve this issue.

**Comment by abshankr** [comment]
We have released ExoPlayer 2.18.1. The dependency issue has been resolved in this version.
