### ISSUE TITLE
HVEC Video in MKV with Embedded VOBSUB subtitles

### ISSUE THREAD

**Issue by rossinior** [amzn/exoplayer-amazon-port#15]
- This issue tracker is intended for bugs, feature requests and ExoPlayer specific questions.

I do  have an ExoPlayer specific question. When DirectPlaying HVEC video content in MKV containers via Plex app on Amazon Fire TV (Fire OS 5.2.4.1) with embedded VOBSUB subtitles selected, the subtitles do not show as overlay. 

Which port of ExoPlayer is being used? Which version? Plex logs do show that Plex thinks tjat everything is fine. But Plex is using the Amazon Fire TV (2nd  gen) ecosystem for playback.

**Comment by peddisri** [comment]
I'm afraid, this question needs to be re-directed to Plex.  Can you please share the MKV video file ?

**Comment by rossinior** [comment]
I shared this with Plex and they say that it is a problem with the device / firmware.
The following discussion thread contains valuable data about the MKV a/v analysis.

https://forums.plex.tv/discussion/264979/subtitles-on-mkv-selectable-but-not-playing-on-amazon-fire-tv-2

When you Review that thread, please Keep in mind that test case A  is the original file which has the Problem. All other scenarii are just there to rule out certain causes. Later in the thread, I explain this in Detail. It is seemingly hard to understand.

How do I share a sample? The original file is very large...

Cheers.

**Comment by peddisri** [comment]
I suggest you share the file via dropbox or some file sharing site. I don't seem to have access to the discussion link you shared since I don't have a Plex Pass membership. I'll check internally if someone has.

**Comment by rossinior** [comment]
I nailed it down to header compression of the VOBSUB subtitle tracks...

The original smaple had two embedded VOBSUB subtitle tracks, both with header compression enabled (zLib compression). When remuxing the sample to just remove the header compression of the subtitle tracks, everything plays flawlessly and subtitles are shown.

Will zLib compressed VOBSUB subtitles be supported?

Here's another threas discussion zLib header compression

https://github.com/google/ExoPlayer/pull/1372
