### ISSUE TITLE
Native crash in Amazon Kindle Fire HD 7" (2013) when trying to play SmoothStreaming SuperSpeed content in ExoPlayer demo app

### ISSUE THREAD

**Issue by moacir69** [amzn/exoplayer-amazon-port#17]
### Issue description
There is a native crash in Amazon Kindle Fire HD 7" (2013) when trying to play SmoothStreaming SuperSpeed content in ExoPlayer demo app.
The same video plays well if Big Buck Bunny (MP4 Video) is played first.

### Reproduction steps
Install ExoPlayer demo app in an Amazon Kindle Fire HD 7" (2013) and attempt to perform the playback of SmoothStreaming SuperSpeed content.

### Link to test content
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
Amazon Kindle Fire HD 7" (2013) / Fire OS 4.5.5.2 / (Init 2.3.1 [soho, KFSOWI, Amazon, 19])

### A full bug report captured from the device
Attached file 'bugReport.txt'
[bugReport.txt](https://github.com/amzn/exoplayer-amazon-port/files/993223/bugReport.txt)

**Comment by peddisri** [comment]
https://github.com/amzn/exoplayer-amazon-port/commit/c64fc56f3f8369a803e9efbd8e8bd924163e6292
