### ISSUE TITLE
CRASH: java.lang.NoClassDefFoundError: android.provider.Settings$Global

### ISSUE THREAD

**Issue by chenqian1024** [amzn/exoplayer-amazon-port#18]
### Issue description
Describe the issue in detail, including observed and expected behavior.
Crash happens for devices on API 16 with stack trace. From Android documentation, Settings.Global only supports API 17 and up.

java.lang.NoClassDefFoundError: android.provider.Settings$Global com.google.android.exoplayer2.audio.AudioCapabilities.getCapabilities(AudioCapabilities.java:66) com.google.android.exoplayer2.audio.AudioCapabilities.getCapabilities(AudioCapabilities.java:59) com.google.android.exoplayer2.SimpleExoPlayer.buildAudioRenderers(SimpleExoPlayer.java:694) com.google.android.exoplayer2.SimpleExoPlayer.buildRenderers(SimpleExoPlayer.java:626) com.google.android.exoplayer2.SimpleExoPlayer.(SimpleExoPlayer.java:157) com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:105) com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:82) com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:62) com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:47) 

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.
Try playing a video on devices on API 16.

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com including the issue number in the subject line.
The issue should happen regardless of media.

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".
2.4.0

### Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.
ZTE_N9511 (OS Version: 4.1.2)
SAMSUNG-GT-I8190N (OS Version: 4.1.2)

**Comment by peddisri** [comment]
Will update this issue soon.

**Comment by peddisri** [comment]
https://github.com/amzn/exoplayer-amazon-port/commit/17e45c01e1d73c1227795ae56d23c7c317f1eb3f
