### ISSUE TITLE
FireOS 5.0.2 Unable to play Super speed (PlayReady) stream.

### ISSUE THREAD

**Issue by alex-schwartzman** [amzn/exoplayer-amazon-port#19]
### Issue description
I have installed the sample application **./gradlew installNoExtensionsDebug** on my FireTV Stick, which runs FireOS 5.0.2 (540049450). The application is capable of playing non-encrypted SmoothStreaming content, but not able playing encrypted one. 

### Reproduction steps
Pre-requisites:
* FireTV Stick with FireOS 5.0.2
* git clone git@github.com:amzn/exoplayer-amazon-port.git
Steps to reproduce:
* ./gradlew installNoExtensionsDebug
* adb shell am start -n com.google.android.exoplayer2.demo/.SampleChooserActivity
* Open SmoothStreaming section
* Click on **Super speed (PlayReady)** item
Expected:
* Stream is playing
Observed:
* Black screen

### Link to test content
Manifest: http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest
LA Url: http://playready.directtaps.net/pr/svc/rightsmanager.asmx?

### Version of ExoPlayer being used
2.4.0, as well as 2.3.1

### Device(s) and version(s) of Android being used
FireTV Stick with FireOS 5.0.2 (540049450)
Issue is NOT reproducible on FireTV gen2.

### A full bug report captured from the device
See the attachment. Full bug report does not fit into 65535 characters allowed.
[bugreport.zip](https://github.com/amzn/exoplayer-amazon-port/files/1130908/bugreport.zip)

**Comment by peddisri** [comment]
Hi,
There is some PlayReady server side customization required to support playback of encrypted content for Fire TV Stick Gen1 and Fire TV Gen1. Please see the note under DRM section in https://developer.amazon.com/public/solutions/devices/fire-tv/docs/device-and-platform-specifications
Thanks!

**Comment by alex-schwartzman** [comment]
I just tried on another FireTV Stick Gen1 device, which already has FireOS 5.2, and the sample PlayReady stream plays without any problem there.

Did you mean that the devices, based on FireOS 5.0 send license requests a bit differently than those more recent ones?

**Comment by peddisri** [comment]
You mean you have two devices, both with same OS version, but they behave differently?

FireOS 5.0.x based legacy devices needed a customization in the server (yes, they license response from server is expected to be slightly different) .  There were some efforts to remove this restriction - I'll need to check if its part of 5.2. So yes, it's possible that when you update from 5.0.2 to latest, this restriction is no longer needed.

**Comment by alex-schwartzman** [comment]
Sorry for the confusion. What I mean is that the pattern for the playback problems is as follows:

Device | FireOS | Reproducible?
------------ | ------------- | -------------
FireTV Stick gen1 | 5.0 | YES
FireTV Stick gen1 | 5.2 | NO
FireTV gen2 | 5.2 | NO

That makes me, as a software vendor, to either adjust licensing proxy (which I cannot do since I buy content and licensing as SaaS), or support older FireOS by avoiding PlayReady, or kindly remind the users to upgrade their devices. Provided that the userbase is very slim, I would opt for the latter.

Thanks for you consideration
Alex.

**Comment by peddisri** [comment]
We enforce software updates to our customers.  No device will be on previous versions when new OS version is released.

**Comment by alex-schwartzman** [comment]
@peddisri yes, I know that Amazon enforces software upgrades. The only problem is that one of the two Fire TV Sticks I have - did not upgrade since 2015. 

Sorry for the offtopic, but seems like handling lower versions of FireOS is still an issue.

**Comment by peddisri** [comment]
Can you send me a private email with your Device Serial number (Settings -> System -> About ) ? I guess you got this device from Amazon? May be it's not in the OTA pool - but all our customer's devices get auto updated without exception. You won't need to worry about lower version of FireOS for customers.
