### ISSUE TITLE
Publish a maven dependency

### ISSUE THREAD

**Issue by se-bastiaan** [amzn/exoplayer-amazon-port#2]
It would be great if this port gets published to jCenter or mavenCentral so that it can be used more easily.

**Comment by peddisri** [comment]
We have published this to jcenter.
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-core
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-hls
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-ui
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-smoothstreaming
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-dash

**Comment by thekarthiksankar** [comment]
@peddisri All the links you have listed above are the broken links

Can you please update the new link?

And if you update in the README.md too it'll be awesome
