### ISSUE TITLE
Add remote gradle dependencies to readme file 

### ISSUE THREAD

**Issue by jandresakis** [amzn/exoplayer-amazon-port#22]
### Issue description
Trying to find the actual remote dependencies requires some google detective work. It should be posted in plain sight and easily accessible.

    compile 'com.amazon.android:exoplayer-core:r2.5.1'
    compile 'com.amazon.android:exoplayer-dash:r2.5.1'
    compile 'com.amazon.android:exoplayer-smoothstreaming:r2.5.1'

### Reproduction steps
Just google search exoplayer-amazon-port and try to find the remote dependencies. It took me a few hours of searching before I came across the mention of some maven dependencies and jcenter.

### Link to test content
n/a

### Version of ExoPlayer being used
n/a

### Device(s) and version(s) of Android being used
n/a

### A full bug report captured from the device
n/a

**Comment by peddisri** [comment]
Thanks for the feedback. We'll add this info in README.

**Comment by peddisri** [comment]
done.
