### ISSUE TITLE
Publish extensions to jcenter

### ISSUE THREAD

**Issue by christianb** [amzn/exoplayer-amazon-port#23]
### Issue description
Please publish extensions like IMA and others to jcenter as you mentioned in the README and in #4 .

### Reproduction steps
`com.amazon.android:extension-ima` and other extensions not available in jcenter
 
### Link to test content
n/a

### Version of ExoPlayer being used
2.5.3

### Device(s) and version(s) of Android being used
n/a

### A full bug report captured from the device
n/a

**Comment by peddisri** [comment]
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/extension-ima

Already published.

**Comment by peddisri** [comment]
https://github.com/amzn/exoplayer-amazon-port/blob/amazon/r2.5.3/README.md
