### ISSUE TITLE
ExoPlayer 2.6

### ISSUE THREAD

**Issue by NicolaVerbeeck** [amzn/exoplayer-amazon-port#25]
Hi. Do you have an estimate of when you expect to update this port to ExoPlayer 2.6?

**Comment by peddisri** [comment]
Do you have an immediate need?  We typically take 15-20 days from Google's release to publish the port.

**Comment by NicolaVerbeeck** [comment]
No immediate need, just need to know for our planning. Thanks!

**Comment by peddisri** [comment]
We are a little pre-occupied with other things. So it might get delayed a bit too. Hope you account for that in your planning.

**Comment by yital9** [comment]
We've recently tested the ExoPlayer 2.6 from Google on FireTV devices and noticed, that it also works without problems (above FireOS 5.2.6.0). Do we still have to use the Amazon port of ExoPlayer? Or perhaps was it necessary for earlier OS versions? 
Could you please explain, which changes does  the Amazon port contain and how critical is it to use it now for new FireOS versions? 
We develop both Android and FireTV apps and it means always a double effort to update the ExoPlayer to a new version. It would be great to know, whether it's still necessary.

**Comment by peddisri** [comment]
You need to look into the top 10 patches and their commit messages to understand if these patches are useful to your use case. Its is possible that you don't need amazon port based on your use case and targeted devices. For example without out patch you won't be able to play any content in FireOS 4 based legacy Kindle tablets.

**Comment by christianb** [comment]
Any new update when the ExoPlayer 2.6 port will come?

**Comment by peddisri** [comment]
We are busy with high priority tasks. Do you absolutely need this?

**Comment by christianb** [comment]
We need it, but we can also wait.

**Comment by peddisri** [comment]
Thank you for your patience. I'll try my best to get it out as soon as possible.

**Comment by christianb** [comment]
Thanks for creating ExoPlayer Port 2.6.1

Will you also create a port for the IMA Extension?

**Comment by peddisri** [comment]
Published 2.6.1 to github and jcenter
