### ISSUE TITLE
Video doesn't stretch to surface on Fire TV with 4K Ultra HD

### ISSUE THREAD

**Issue by nikbjork** [amzn/exoplayer-amazon-port#26]
### Issue description
DASH templated dynamic manifest with video segments that have non square pixels (sar = 64:45) and non 16:9 or 4:3 par does not stretch to produce correct dar. We read the size from each segment and the SurfaceView is stretched to correct aspect-ratio but the video is squished together based on the size of the video (see screenshot).
![img_20171130_140328](https://user-images.githubusercontent.com/8478203/33435121-a06baf94-d5e1-11e7-8f54-46527492fa5c.jpg)

### Reproduction steps
Play a video with 66:45 sar segments.

### Link to test content
I can provide a unencrypted stream through email

### Version of ExoPlayer being used
2.5.4 and 2.6.0

### Device(s) and version(s) of Android being used
Fire TV with 4K Ultra HD (https://www.amazon.com/all-new-amazon-fire-tv-4k-uhd-streaming-media-player/dp/B01N32NCPM)

**Comment by peddisri** [comment]
Please send the URL to pii-Exoplayer-core@amazon.com

**Comment by peddisri** [comment]
This fix is being OTAed currently.
