### ISSUE TITLE
Video and player freezes when switching quality levels in HLS

### ISSUE THREAD

**Issue by elcolto** [amzn/exoplayer-amazon-port#27]
### Issue description
For m3u8 master playlists containing multiple quality levels, Exoplayer freezes when switching quality level. When only a single quality level is existing, the video plays as expected. This issue occurs on version 2.5.x, on version 2.4.x everything works as expected. 

### Reproduction steps
Call `exoPlayer.prepare(new HlsMediaSource(uri, factory, null, null))` and `exoPlayer.setPlayWhenReady(true)` with provided streaming url.

### Link to test content
Working and non working stream url was provided via email.

### Version of ExoPlayer being used
```
"com.amazon.android:exoplayer-core:r2.5.4"
"com.amazon.android:exoplayer-hls:r2.5.4"
"com.amazon.android:exoplayer-ui:r2.5.4"
"com.amazon.android:extension-okhttp:r2.5.4"
```
### Device(s) and version(s) of Android being used
FireTV 3rd gen. FireOS 6.2.1.2
On Android TV devices playback works fine

### A full bug report captured from the device
[log.txt](https://github.com/amzn/exoplayer-amazon-port/files/1606021/log.txt)

**Comment by peddisri** [comment]
Unable to repro this issue. The bitrate switches smoothly to higher levels on Fire TV 3rd Gen FireOS6 device.Tested with 2.6.1 and 2.5.4. 

From your logs I see
"01-05 09:40:24.482 14972-15320/com.example.android E/ACodec: dequeueBuffer failed: NO_INIT(-19)."  which could be the reason for freeze. But I'm unable to repro this issue at all.  

Is this reproduced always?
