### ISSUE TITLE
Jitpack build fails

### ISSUE THREAD

**Issue by romanbsd** [amzn/exoplayer-amazon-port#32]
### Issue description
jitpack.io build fails:
<pre>
/home/jitpack/build/library/core/src/main/java/com/google/android/exoplayer2/offline/SegmentDownloader.java:268: error: reference not found
   * @see #getSegments(DataSource, M, Object[], boolean)
          ^
</pre>
https://jitpack.io/com/github/amzn/exoplayer-amazon-port/80c42211/build.log
Probably because the signature has changed and now #getSegments(DataSource, M, Object[], K[], boolean)

### Reproduction steps
Build on jitpack

### Version of ExoPlayer being used
commit 80c42211

**Comment by peddisri** [comment]
Does this pass in google's version?

**Comment by romanbsd** [comment]
No idea, we are using the google version from maven repo, not via jitpack.

**Comment by peddisri** [comment]
Fixed in 2.6.1 branch
