### ISSUE TITLE
dependency issue failed to resoved

### ISSUE THREAD

**Issue by mahesh2015** [amzn/exoplayer-amazon-port#36]
Error:Failed to resolve: com.amazon.android:extension-ima:2.6.1

Error:Failed to resolve: com.amazon.android:extension-mediasession:2.6.1

Error:Failed to resolve: com.amazon.android:extension-rtmp:2.6.1

**Comment by peddisri** [comment]
We are trying to find out the reason for this failure. not all libs download fail though. Its quite weird.

**Comment by mahesh2015** [comment]
This is my all dependencies
```
dependencies {
  // Glide image library
    implementation 'com.github.bumptech.glide:glide:4.6.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'
    compile "com.android.support:support-v4:$supportLibraryVersion"
    compile "com.android.support:appcompat-v7:$supportLibraryVersion"
    compile 'com.google.android.gms:play-services-analytics:11.8.0'
    compile 'com.android.volley:volley:1.1.0'
     compile 'com.android.support:multidex:1.0.3'

    compile "com.amazon.android:exoplayer:$exoplayerVersion"
    compile "com.amazon.android:exoplayer-core:$exoplayerVersion"
    compile "com.amazon.android:exoplayer-hls:$exoplayerVersion"
    compile "com.amazon.android:exoplayer-dash:$exoplayerVersion"
    compile "com.amazon.android:exoplayer-smoothstreaming:$exoplayerVersion"
    compile "com.amazon.android:exoplayer-ui:$exoplayerVersion"
    compile "com.amazon.android:extension-gvr:$exoplayerVersion"
    compile "com.amazon.android:extension-ima:$exoplayerVersion"
    compile "com.amazon.android:extension-mediasession:$exoplayerVersion"
    compile "com.amazon.android:extension-okhttp:$exoplayerVersion"
    compile "com.amazon.android:extension-rtmp:$exoplayerVersion"
    compile files('libs/WebtrendsAndroidClientLib.jar')
}

ext {
    supportLibraryVersion = '27.0.2'
    playServicesVersion = '11.8.0'
    exoplayerVersion = '2.6.1'
}
```

**Comment by peddisri** [comment]
by the way, do you really need all the extensions for your app/project?

**Comment by mahesh2015** [comment]
No, All are not required, But i need ima-extension and hls with core lib.

**Comment by mahesh2015** [comment]
@peddisri  any update for "_Error:Failed to resolve: com.amazon.android:extension-ima:2.6.1_"

**Comment by jkwiz** [comment]
I had the same problem. I believe this is because the extensions are not linked to jcenter like the core and others, and used the following workaround in the mean time:

```
compile ("com.google.android.exoplayer:extension-ima:2.6.1", {
    exclude group: 'com.google.android.exoplayer'
})
```

**Comment by peddisri** [comment]
@jkwiz Thank you, indeed that is the problem. Since these were new extensions added since we hosted the binaries in jcenter, we have to individually ask bintray to add these libraries to jcenter. I've sent a request and hopefully within a day they should approve.  You may try this after a couple of days and it should work.

**Comment by peddisri** [comment]
Ok its approved. can you try this and let me know if it works.

**Comment by jkwiz** [comment]
Looking good here, thanks!

**Comment by mahesh2015** [comment]
Thanks @peddisri , Now it's working fine.
