### ISSUE TITLE
FireOS 5 and above question.

### ISSUE THREAD

**Issue by bertbb24** [amzn/exoplayer-amazon-port#39]
### Issue description
Our app appears to work fine with the official google exoplayer release for FireOS 5 and above. Is it recommended to use the google version or should the amazon port always be used (if we are only targeting FireOS 5 and above).

thank you in advance.

**Comment by peddisri** [comment]
Using Amazon's Port is required only if the patches addresses issues faced by your app. It is mainly required if 
1. Content has Dolby Audio
2. Content is PlayReady protected.
3. You need to target Fire OS 4 based legacy tablets.

My suggestion is to go through the commit messages of the ~10 patches that we have and then check if you really need them.
