### ISSUE TITLE
Failed to resolve: com.amazon.android:exoplayer-smoothstreaming:2.7.1

### ISSUE THREAD

**Issue by christianb** [amzn/exoplayer-amazon-port#40]
Failed to resolve: com.amazon.android:exoplayer-smoothstreaming:2.7.1

Other module dependencies (core, ui, hls, dash) are working fine.

**Comment by peddisri** [comment]
Thank you for reporting this issue. We are taking a look at it. Will update as soon as we have a solution.

**Comment by peddisri** [comment]
This is fixed now.
