### ISSUE TITLE
com.amazon.android:exoplayer:2.7.1 does not fetch any module dependency

### ISSUE THREAD

**Issue by christianb** [amzn/exoplayer-amazon-port#41]
`com.amazon.android:exoplayer:2.7.1` does not fetch any other module dependencies.

We could add those module dependencies separately but we need all of them. So prior to 2.7.1 we were able to fetch them all within one dependency declaration as it was possible until 2.6.1

**Comment by peddisri** [comment]
work in progress. 2.7.1 will not be available temporarily in jcenter till we fix this.

**Comment by peddisri** [comment]
2.7.1 is now available for download, and this issue is fixed. Can you verify at your end?

**Comment by christianb** [comment]
I still does not fetch the modules...

**Comment by aditya-yo** [comment]
Hi @christianb ,
Did you try clearing gradle cache and then syncing Gradle?
You can find it in $HOME/.gradle/caches
It worked for me.

**Comment by christianb** [comment]
That seems to work. Thanks :)
