### ISSUE TITLE
Update to ExoPlayer v2.8.0

### ISSUE THREAD

**Issue by NitroXenon** [amzn/exoplayer-amazon-port#45]
ExoPlayer v2.8.0 has been released. There are many new features and bug fixes in v2.8.0. Applications requiring the latest ExoPlayer version cannot currently be built for Amazon hardware. It would be very great if we could use the latest version of ExoPlayer in our apps on Amazon App Store and make our apps better at the earliest.

@peddisri

**Comment by peddisri** [comment]
work in progress. There are many changes in the DefaultAudioSink which means our patches needs rework and more test coverage.

**Comment by NitroXenon** [comment]
ok thanks!

**Comment by peddisri** [comment]
release in github and jcenter

**Comment by NitroXenon** [comment]
@peddisri Cool, thanks!

Today 2.8.1 has been released and some new bugs in 2.8.0 have been fixed. Would you mind take a look at it? Thanks.

**Comment by peddisri** [comment]
2.8.1 update done
