### ISSUE TITLE
How to install on a FireTV Stick?

### ISSUE THREAD

**Issue by neik1** [amzn/exoplayer-amazon-port#47]
First of all I am sorry if this isn't the right place to post this but I didn't know where else to go.

I want to test the Exoplayer on my FireTV Stick (Gen 2) but unfortunately I do not know how I do compile this to an .apk in order to install it on the FTVS - only found a Demo version of the Exoplayer.

Any hint is appreciated, best case would be a compiled apk.
Thanks!

**Comment by peddisri** [comment]
u can compile this by  "./gradlew assemble"   this will create a APK in demos/main/buildOut folder
