### ISSUE TITLE
Unable to play Super speed (PlayReady) stream on Amazon Fire TV Generation 1 (AFTB/Bueller)

### ISSUE THREAD

**Issue by nahojkap** [amzn/exoplayer-amazon-port#53]
This issue is related to https://github.com/amzn/exoplayer-amazon-port/issues/19 but applies only to the Amazon Fire TV Gen 1 (AFTB/Beuller).  I used isse 19 as a template for this issue.

I am aware of the issue playing encrypted audio content on some devices but since the Amazon FireTV Stick Generation 1 can play this content correctly, it would be nice to have consistent playback also on this device.

Issue description
---
I have installed the sample application ./gradlew installNoExtensionsDebug on my FireTV AFTB (Bueller), which runs FireOS 5.2.6.6 (617513120). 

The application is capable of playing non-encrypted SmoothStreaming content, but not able playing encrypted ones.

Reproduction steps
---

Pre-requisites:
----
FireTV Stick with FireOS 5.2.6.6

git clone git@github.com:amzn/exoplayer-amazon-port.git

Steps to reproduce:

./gradlew installNoExtensionsDebug
adb shell am start -n com.google.android.exoplayer2.demo/.SampleChooserActivity
Open SmoothStreaming section
Click on Super speed (PlayReady) item

Expected:
Stream is playing

Observed:
Exception/playback error

04 12:11:41.980 11154 11154 D EventLogger: decoderInitialized [1.39, 0.00, window=0, period=0, audio, OMX.google.aac.decoder]
09-04 12:11:41.981 11154 11154 D EventLogger: downstreamFormatChanged [1.39, 0.00, window=0, period=0, id=null, mimeType=audio/mp4a-latm, bitrate=128000, channels=2, sample_rate=44100]
09-04 12:11:41.982   751 12584 E PlayReady: playready_decrypt_audio rsp msg failed and returned ret = -2147164163
09-04 12:11:41.982   751 12584 E pr_crypto_plugin: Operate:: the playready_decrypt_audio failed and returns = -2147164163
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: Internal runtime error.
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: android.media.MediaCodec$CodecException: Error 0x8004dffd
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:978)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:813)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:608)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:135)
09-04 12:11:41.983 11154 13291 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-04 12:11:41.983 11154 13291 I OMX.qcom.video.decoder.avc.secure-MediaCodecRenderer: releaseCodec

Link to test content
Manifest: 

http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest
LA Url: http://playready.directtaps.net/pr/svc/rightsmanager.asmx?

Version of ExoPlayer being used
2.8.4

Device(s) and version(s) of Android being used

FireTV Stick with FireOS 5.2.6.6 (617513120)

Issue is NOT reproducible on FireTV Stick Generation 1.  

A full bug report captured from the device

See the attachment. Full bug report does not fit into 65535 characters allowed.
playback-pr-protected-ms-test-content.zip

**Comment by nahojkap** [comment]
[playback-pr-protected-ms-test-content.zip](https://github.com/amzn/exoplayer-amazon-port/files/2349526/playback-pr-protected-ms-test-content.zip)

**Comment by peddisri** [comment]
Yes, you won't be able to play default playready stream on Fire TV Gen1.  If you want to use PlayReady DRM for your content then you need to do a minor configuration change in PlayReady licence server. To know more about this, please get in touch with the Amazon Developer Support.
