### ISSUE TITLE
When do you want to roll out an update to actual exoplayer version 2.9.0?

### ISSUE THREAD

**Issue by userdimi** [amzn/exoplayer-amazon-port#55]

**Comment by peddisri** [comment]
We are bogged down by critical priority issues, hence the delay. Are you blocked on this update? We plan to do this in Nov (or take the latest one available in Nov).

**Comment by userdimi** [comment]
@peddisri Thank you for your quick response. Yes at the moment I'm blocked because I want to use the
 ` 
    public ParametersBuilder setForceHighestSupportedBitrate(boolean forceHighestSupportedBitrate) {
      this.forceHighestSupportedBitrate = forceHighestSupportedBitrate;
      return this;
    }` 
method that was added in the last exoplayer update

**Comment by davemt** [comment]
We need to use the new `LoadErrorHandlingPolicy` capabilities in `2.9.0`.

**Comment by peddisri** [comment]
We are working on it. Stay tuned.

**Comment by rinoshs** [comment]
2.9.0 had been published to bintray.  We will pubish it on github soon.

**Comment by rinoshs** [comment]
Exoplayer 2.9.0 has been published to github.

**Comment by userdimi** [comment]
Thank you. Great work!
