### ISSUE TITLE
Get a version string that differs from non-forked Exoplayer?

### ISSUE THREAD

**Issue by johanneskraem3r** [amzn/exoplayer-amazon-port#57]
In an app with two configurations ( one for Amazon devices, one for non-Amazon Android devices ), I would like to print a version string for Q&A. 

ExoPlayerLibraryInfo.VERSION_SLASHY seemed like a good candidate, but I was suprised to see that this String in the fork is the same exact one as in the original Exoplayer:

  https://github.com/amzn/exoplayer-amazon-port/blob/5fba4b76785b98cc8d00fbbc7dbbd367424e78bd/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerLibraryInfo.java#L36  

Is there a way to get a "version string" for this lib that clearly shows that it's the fork and not the original?

**Comment by peddisri** [comment]
There are other ways of figuring out whether this is Amazon's port or Google's original. If you just want to check this from the logs I can help you with that. 
You could look out for this log line:
https://github.com/amzn/exoplayer-amazon-port/blob/amazon/r2.8.4/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L367

**Comment by johanneskraem3r** [comment]
Thanks, looking for the log output is certainly a good way to check if it's the fork in the logs.

What I'm looking for is something I can check in code.

Is there any chance there's a value also present in the in non-Amazon exoplayer, that returns a different value for the fork?

**Comment by peddisri** [comment]
Change request accepted. Will work on it.

**Comment by rinoshs** [comment]
This change is present in r2.9.0 on github and bintray.

public static final String VERSION_SLASHY = "AmznExoPlayerLib/2.9.0";
