### ISSUE TITLE
Add Fling to amazon-Exoplayer

### ISSUE THREAD

**Issue by 94pvasilev** [amzn/exoplayer-amazon-port#6]
Adding fling to the ExoPlayer can be really helpfull to promote your SDK - **Feature**

**Comment by peddisri** [comment]
Fling is a feature of the demo app , and not ExoPlayer library.  This is a good suggestion, but right now we have no plans to add this feature in ExoPlayer Demo app. 

Amazon Fire TV supports DIAL for flinging to second screen.  You can refer to these developer docs https://developer.amazon.com/public/solutions/devices/fire-tv/docs/dial-integration to understand how to integrate DIAL into your app.  

We would let you know if we plan to add this in future.
