### ISSUE TITLE
Change package?

### ISSUE THREAD

**Issue by fougere-mike** [amzn/exoplayer-amazon-port#78]
### Issue description

It is my understanding that Amazon chose to port ExoPlayer because there were amazon-specific changes that were either not compatible or not accepted by google's ExoPlayer project.

Due to the fragmentation, I would prefer to use the amazon ExoPlayer port on _amazon devices_, and google's ExoPlayer on _non-amazon devices_.

This is where the issue comes in: I require the ability to create a single APK which works on both google and amazon devices. 

Currently, it is not possible to include _both_ versions of ExoPlayer in a single project because of package name conflicts. A possible solution would be to build separate APKs for each platform, but that is undesirable.

So, I wonder if the Amazon ExoPlayer team would consider moving the sources under an "amazon" package to get around the conflicts and allow both ExoPlayers to exist together.

**Comment by peddisri** [comment]
Well, we take extra caution to make sure our port works on non-amazon devices i.e our changes do not impact the behavior on other devices.  Most of our changes are enabled/targeted for specific amazon devices controlled by AmazonQuirks.java. 

Changing package name is not something we would encourage. I'm sure Android studio / gradle build system allows multiple flavors of APKs that can use different libs.
