### ISSUE TITLE
Exoplayer 2.0

### ISSUE THREAD

**Issue by mlondon1** [amzn/exoplayer-amazon-port#8]
Hi,
When do you expect to support Exoplayer 2 on Amazon devices?  Exoplayer 2 fixed an issue for our Widevine-Dash content on Android devices

https://github.com/google/ExoPlayer/issues/1813

**Comment by peddisri** [comment]
We are planning supporting Exo 2.x , but since it there are major changes, it may take more time that 1.x updates.  For a quick solution to your problem,can you backport the specific patch that fixes your issue in 1.x?

**Comment by mlondon1** [comment]
We are not sure of the exact fix

**Comment by peddisri** [comment]
What Amazon Platforms are you targeting? Is WV your only DRM scheme? Do you target Kindle Tablets too?  The reason why I ask this is that if you look at the handful of patches for Amazon devices, they specifically target PlayReady and Dolby content. Which patch is really essential for you based on what it addresses?

**Comment by peddisri** [comment]
I read your original post in Google github. For now, can you continue to use 1.x for Amazon and other non-Android devices where this issue is not seen and upgrade to 2.x only for the samsung devices that exhibits this issue?

**Comment by boywithk9** [comment]
Is there any news on when we can expect the Exoplayer 2.1 Amazon port?

**Comment by peddisri** [comment]
In this week we will release 2.0.3 and 2.0.4. Thank you for your patience!  Upmerging to 2.1 should happen in  a  week ,hopefully it will be straightforward

**Comment by peddisri** [comment]
2.1.1 pushed.
