### ISSUE TITLE
How can we play Dash format urls (manifest files) in Amazon Firestick App by using Android SDK?

### ISSUE THREAD

**Issue by Maneesh528** [amzn/exoplayer-amazon-port#82]
Hello Team, I am developing an App for Amazon Firestick, My requirement is to play m3u8 and manifest format videos in my app. m3u8 is working great, facing issue while playing the manifest format url's. Can any one help me to get out of this issue. Thanks in advance

**Comment by rinoshs** [comment]
What do you mean by manifest format videos?  Do you have a sample video?

**Comment by Maneesh528** [comment]
Thanks for your reply Rinsohs, I have fixed the issue
