### ISSUE TITLE
Is there a list maintained anywhere of the fixes for Amazon devices that are not currently in the vanilla Exoplayer project?

### ISSUE THREAD

**Issue by Jogan** [amzn/exoplayer-amazon-port#83]

**Comment by victorraft** [comment]
I would love to know that as well.

**Comment by tmm1** [comment]
See https://github.com/amzn/exoplayer-amazon-port/commits/amazon/r2.9.0

**Comment by rinoshs** [comment]
The commit history for the latest release is the best way to see the amazon fixes.  All the amazon fixes will be on top of vanilla ExoPlayer.

**Comment by Jogan** [comment]
Thank you! Might be nice to add this into the README for this project.
