### ISSUE TITLE
Can we integrate youtube API in Fireapp Builder? If No Can you please suggest the best approach to play the Youtube Urls. 

### ISSUE THREAD

**Issue by Maneesh528** [amzn/exoplayer-amazon-port#84]
Hello Team, I am developing an App for Amazon FireTV by using Fireapp Builder. How can I play Youtube Urls in it ?

**Comment by Maneesh528** [comment]
Hello, Can any one suggest the solution for Can we integrate youtube API in Fireapp Builder? If No Can you please suggest the best approach to play the Youtube Urls.

**Comment by rinoshs** [comment]
Have you checked with the Fireapp Builder team?   In Exoplayer, the demo app has examples of playing youtube videos.
