### ISSUE TITLE
Update to Exoplayer 2.9.4

### ISSUE THREAD

**Issue by userdimi** [amzn/exoplayer-amazon-port#86]
The Google Exoplayer 2.9.4 version contains  a fix for this [issue](https://github.com/google/ExoPlayer/issues/5240). This issue affect a lot of user in my app at the moment. Can you please integrate this fix in your Exoplayer fork? 

Thanks a lot.

**Comment by rinoshs** [comment]
We are working on this.

**Comment by rinoshs** [comment]
Updated to 2.9.6 on github & bintray

**Comment by userdimi** [comment]
@rinoshs Thank you very much.
