### ISSUE TITLE
Build Support for Open Measurement by updating Exoplayer extension.

### ISSUE THREAD

**Issue by ocorso** [amzn/exoplayer-amazon-port#87]
Exoplayer extension v2.9.6 will be released on 2/18/2019. 

To realize the added functionality, this Amazon port will need to integrate the new changes which include the ability to register new elements and the registration of default Exoplayer overlays.

Here's the new IMA SDK API documentation related to Open Measurement:
https://docs.google.com/document/d/1ECUW4cgsH_KR1sjfUXgP6bJ3Lig_9uj6HHQ5qFT6rQI/edit

**Comment by rinoshs** [comment]
The document link above is read protected.

**Comment by ocorso** [comment]
My bad - here's an externally-friendly link: https://bit.ly/omid-guide
Let me know if you have questions: ocorso@google.com

**Comment by rinoshs** [comment]
Updated to 2.9.6 on github and bintray.
