### ISSUE TITLE
Amazon port and compatibility with FireOS 4.x

### ISSUE THREAD

**Issue by boywithk9** [amzn/exoplayer-amazon-port#9]
In the Supported Devices page of your regular ExoPlayer documentation (https://google.github.io/ExoPlayer/supported-devices.html), you refer to incompatibilities affecting FireOS version 4 and earlier. Does your Amazon port work around those issues, or would devices with FireOS 4.x still exhibit those bugs, even with the current version of your Amazon port?

**Comment by peddisri** [comment]
Yes, this port work around those issues.
