### ISSUE TITLE
General question on the purpose of that fork

### ISSUE THREAD

**Issue by AfanasievAnton** [amzn/exoplayer-amazon-port#93]
### [REQUIRED] Searched documentation and issues
I was looking into commit history of the repo.

### [REQUIRED] Question
I just browsed for the latest commits and fixes for this repo and did not see any updates lately. (at least anything major for a last 6 month).
That is why I am wondering about the purpose of that fork? Does it contain/fix amzn specific issues that latest exoplayer does not do? And if so what are this issues?
I just want to understand the pros/cons of using your library for amzn tv.
Thank you in advance.

**Comment by rinoshs** [comment]
Look at the top of the commit history below for the amazon specific fixes.  The fixes are for amazon specific devices like FireTV that are not present in Vanilla ExoPlayer.

https://github.com/amzn/exoplayer-amazon-port/commits/amazon/r2.10.1
