### ISSUE TITLE
Amazon ports of Exo 2.10.6

### ISSUE THREAD

**Issue by ssenanayake** [amzn/exoplayer-amazon-port#95]
Quick question.... has Amazon ports of Google Exo no longer happening ?

If so, is it because Google Exo now works on Amazon devices. (Though we have not tested on much older devices like the "Stick 1")

Thanks

**Comment by aditya-gu** [comment]
Hi @ssenanayake,
Thank you for A2A.
We have ExoPlayer 2.10.6 with Amazon changes available on GitHub.
Kindly let us know if there're any issues.
