### ISSUE TITLE
Update to Exoplayer 2.11.x

### ISSUE THREAD

**Issue by lwld** [amzn/exoplayer-amazon-port#98]
Google ExoPlayer v2.11.0 has recently been released (https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md). In order to be able to use the latest features, apps using both Google and Amazon builds would need and updated Amazon port.

### [REQUIRED] Use case description
Upgrade app to use ExoPlayer 2.11.0 in both Google and Amazon builds

### Proposed solution
Upgrade Amazon port to version 2.11.x of ExoPlayer

**Comment by AndreasGB** [comment]
This would be important to us as well.

**Comment by ebr11** [comment]
Hi.  Any timeline for this?  They are at 2.11.2 now.

**Comment by aditya-gu** [comment]
Hi all,
Thank you for the request.
We are working on it.
We will update as soon as we release the new version. :)

**Comment by AndreasGB** [comment]
Thank you very much for the reply and that you are working on it, appreciate it :)

**Comment by aditya-gu** [comment]
Hi all,
We have ExoPlayer 2.11.3 with Amazon changes available on GitHub.
Kindly let us know if there are any concerns.

Thanks.
